konstantins-buts/jg-java-1-online-spring-tuesday-2022

src/main/java/students/konstantins_buts/lesson_2/level_1/task_1/Task1.java

Reverts konstantins-buts/jg-java-1-online-spring-tuesday-2022#3

Revert "homework"

---

src/main/java/students/konstantins_buts/lesson_2/level_1/task_1/Task1.java
src/main/java/students/sergey_nichiporenko/lesson_2/level_1/task_1/Task1.java

Revert changes in demonstration file and repackage

Lesson 2 Level 1 Task 1

---

src/main/java/students/viktors_maksimovs/lesson_2/level_1/task_2/Task2.java

Lesson 2, Level 1, Task 2

---

src/main/java/students/viktors_maksimovs/lesson_2/level_2/task_4/Phone.java

Lesson 2, Level 2, Task 4

---

src/main/java/students/viktors_maksimovs/lesson_2/level_2/task_5/Task5.java

Lesson 2, Level 2, Task 5

---

src/main/java/students/viktors_maksimovs/lesson_2/level_2/task_6/Task6.java

Lesson 2, Level 2, Task 6

---

src/main/java/students/viktors_maksimovs/lesson_2/level_2/task_8/Task8.java

Lesson 2, Level 2, Task 8

---

src/main/java/students/viktors_maksimovs/lesson_2/level_3/task_9/Task9.java

Lesson 2, Level 3, Task 9

---

src/main/java/students/viktors_maksimovs/lesson_2/level_3/task_10/Task10.java

Lesson 2, Level 3, Task 10

---

src/main/java/students/viktors_maksimovs/lesson_2/level_3/task_11/Task11.java

Lesson 2, Level 3, Task 11

---

src/main/java/students/viktors_maksimovs/lesson_2/level_5/task_18/Task18.java

Lesson 2, Level 5, Task 18

---

src/main/java/students/viktors_maksimovs/lesson_2/level_6/task_23/Task23.java

Lesson 2, Level 6, Task 23

---

src/main/java/students/viktors_maksimovs/lesson_2/level_6/task_24/Task24.java

Lesson 2, Level 6, Task 24

---

src/main/java/students/viktors_maksimovs/lesson_2/level_7/task_28/SumTwoNumbers.java

Lesson 2, Level 7, Task 28

---

src/main/java/students/viktors_maksimovs/lesson_2/level_7/task_29/CorrectDataTypes.java

Lesson 2, Level 7, Task 29

---

src/main/java/students/viktors_maksimovs/lesson_2/level_7/task_31/Task31.java

Lesson 2, Level 7, Task 31

---

src/main/java/students/aleksandrs_binduks/lesson_2/level_1/task_1/Task_1.java

St aleksandrs binduks lesson 2 level 1 task 1

---

src/main/java/students/viktors_maksimovs/lesson_3/level_2/task_7/Task7.java
src/main/java/students/viktors_maksimovs/lesson_3/level_2/task_7/Task8.java
src/main/java/students/viktors_maksimovs/lesson_3/level_2/task_7/Task9.java

Lesson 3, Level 2, Task 7 - Task 9

Lesson 3, Level 2, Task 7 - Task 9

---

src/main/java/students/georgy_bakulin/lesson_3/level_5/task_18/Dog.java
src/main/java/students/georgy_bakulin/lesson_3/level_5/task_18/DogDemo.java
src/main/java/students/georgy_bakulin/lesson_3/level_5/task_19/Dog.java
src/main/java/students/georgy_bakulin/lesson_3/level_5/task_19/DogDemo.java

i mess with main branch in ex 18 and pushed too much .the last one is correct .if its possible to delete others requests in ex 18 except last commit .

St georgy bakulin lesson 3 level 5 task 19 2

---

src/main/java/students/viktors_maksimovs/lesson_4/task_1/Task1.java
src/main/java/students/viktors_maksimovs/lesson_4/task_2/Task2.java
src/main/java/students/viktors_maksimovs/lesson_4/task_3/Task3.java

Lesson 4, Level 1, Task 1 - Task 3

Lesson 4, Level 1, Task 1 - Task 3

---

src/main/java/students/viktors_maksimovs/lesson_4/level_2/task_1/Task4.java
src/main/java/students/viktors_maksimovs/lesson_4/level_2/task_5/Task5.java
src/main/java/students/viktors_maksimovs/lesson_4/level_2/task_6/Task6.java

Lesson 4, Level 2, Task 4 - Task 6

Lesson 4, Level 2, Task 4 - Task 6

---

src/main/java/students/viktors_maksimovs/lesson_4/level_6/task_16/Stock.java
src/main/java/students/viktors_maksimovs/lesson_4/level_6/task_16/StockDemo.java
src/main/java/students/viktors_maksimovs/lesson_4/level_6/task_16/StockTest.java

Lesson 4, Level 6

---

src/main/java/students/viktors_maksimovs/lesson_4/level_4/task_10/Calculator.java
src/main/java/students/viktors_maksimovs/lesson_4/level_4/task_10/CalculatorTest.java

Lesson 4, Level 4, Task 10 - Task 14

Lesson 4, Level 4, Task 10 - Task 14

---

src/main/java/students/viktors_maksimovs/lesson_4/level_7/task_17/FizzBuzz.java
src/main/java/students/viktors_maksimovs/lesson_4/level_7/task_17/FizzBuzzTest.java
src/main/java/students/viktors_maksimovs/lesson_4/level_7/task_18/LeapYear.java
src/main/java/students/viktors_maksimovs/lesson_4/level_7/task_18/LeapYearTest.java
src/main/java/students/viktors_maksimovs/lesson_4/level_7/task_19/Calculator.java
src/main/java/students/viktors_maksimovs/lesson_4/level_7/task_19/CalculatorTest.java
src/main/java/students/viktors_maksimovs/lesson_4/level_7/task_20/LightColorDetector.java
src/main/java/students/viktors_maksimovs/lesson_4/level_7/task_20/LightColorDetectorTest.java

Lesson 4, Level 7

---

src/main/java/students/viktors_maksimovs/lesson_5/level_3/task_16/Task16.java
src/main/java/students/viktors_maksimovs/lesson_5/level_3/task_17/Task17.java
src/main/java/students/viktors_maksimovs/lesson_5/level_3/task_18/Task18.java
src/main/java/students/viktors_maksimovs/lesson_5/level_3/task_19/Task19.java
src/main/java/students/viktors_maksimovs/lesson_5/level_3/task_20/Task20.java
src/main/java/students/viktors_maksimovs/lesson_5/level_3/task_21/Task21.java
src/main/java/students/viktors_maksimovs/lesson_5/level_3/task_22/Task22.java
src/main/java/students/viktors_maksimovs/lesson_5/level_3/task_23/Task23.java
src/main/java/students/viktors_maksimovs/lesson_5/level_3/task_24/Task24.java
src/main/java/students/viktors_maksimovs/lesson_5/level_4/task_25/ArrayDemo.java
src/main/java/students/viktors_maksimovs/lesson_5/level_4/task_26/ArrayRandom.java
src/main/java/students/viktors_maksimovs/lesson_5/level_4/task_27/ArrayHighest.java
src/main/java/students/viktors_maksimovs/lesson_5/level_4/task_28/ArrayLowest.java
src/main/java/students/viktors_maksimovs/lesson_5/level_4/task_29/ArrayEven.java
src/main/java/students/viktors_maksimovs/lesson_5/level_4/task_30/ArrayOdd.java

Lesson 5, Level 3-4

---

src/main/java/students/viktors_maksimovs/lesson_5/level_5/ArrayDemo.java
src/main/java/students/viktors_maksimovs/lesson_5/level_5/ArrayTest.java
src/main/java/students/viktors_maksimovs/lesson_5/level_5/Arrays.java

Lesson 5, Level 5-6

---

src/main/java/instructor/lesson_5/demo_3/Demo3.java
src/main/java/students/vlad_stus/lesson_5/level_1/Task_1.java
src/main/java/students/vlad_stus/lesson_5/level_1/Task_2.java
src/main/java/students/vlad_stus/lesson_5/level_1/Task_4.java
src/main/java/students/vlad_stus/lesson_5/level_1/Task_5.java
src/main/java/students/vlad_stus/lesson_5/level_1/Task_7.java
src/main/java/students/vlad_stus/lesson_5/level_1/Task_8.java
src/main/java/students/vlad_stus/lesson_5/level_1/Task_9.java
src/main/java/students/vlad_stus/lesson_5/level_2/Task_10.java
src/main/java/students/vlad_stus/lesson_5/level_2/Task_11.java
src/main/java/students/vlad_stus/lesson_5/level_2/Task_12.java
src/main/java/students/vlad_stus/lesson_5/level_2/Task_13.java
src/main/java/students/vlad_stus/lesson_5/level_2/Task_14.java
src/main/java/students/vlad_stus/lesson_5/level_2/Task_15.java
src/main/java/students/vlad_stus/lesson_5/level_3/Task_16.java
src/main/java/students/vlad_stus/lesson_5/level_3/Task_19.java
src/main/java/students/vlad_stus/lesson_5/level_3/Task_24.java
src/main/java/students/vlad_stus/lesson_5/level_4/Task_25.java
src/main/java/students/vlad_stus/lesson_5/level_4/Task_26.java
src/main/java/students/vlad_stus/lesson_5/level_4/Task_27.java
src/main/java/students/vlad_stus/lesson_5/level_4/Task_28.java
src/main/java/students/vlad_stus/lesson_5/level_4/Task_29.java
src/main/java/students/vlad_stus/lesson_5/level_5/Task_31/Arrays.java
src/main/java/students/vlad_stus/lesson_5/level_5/Task_31/ArraysTest.java

Done till level 6 included all

St vlad stus lesson 5 level 1

---

src/main/java/students/viktors_maksimovs/lesson_6/level_4/task_18/ForInfiniteLoop.java
src/main/java/students/viktors_maksimovs/lesson_6/level_4/task_18/WhileInfiniteLoop.java
src/main/java/students/viktors_maksimovs/lesson_6/level_4/task_19/ForInfiniteLoopBreak.java
src/main/java/students/viktors_maksimovs/lesson_6/level_4/task_19/WhileInfiniteLoopBreak.java
src/main/java/students/viktors_maksimovs/lesson_6/level_4/task_20/ForLoopContinue.java
src/main/java/students/viktors_maksimovs/lesson_6/level_4/task_20/WhileLoopContinue.java
src/main/java/students/viktors_maksimovs/lesson_6/level_4/task_21/TwoDimensionalArray.java
src/main/java/students/viktors_maksimovs/lesson_6/level_4/task_21/TwoDimensionalArrayDemo.java

я застрял на таске с двухмерным массивом
не понимаю как мне посчитать сумму

Lesson6 level 4

---

src/main/java/students/viktors_maksimovs/lesson_6/level_5/TicTacToe.java
src/main/java/students/viktors_maksimovs/lesson_6/level_5/TicTacToeDemo.java
src/main/java/students/viktors_maksimovs/lesson_6/level_5/TicTacToeTest.java

Lesson 6, level 5
застрял на Draw

Lesson 6, level 5

---

src/main/java/students/georgy_bakulin/lesson_4/level_4/task_10/Calculator.java
src/main/java/students/georgy_bakulin/lesson_4/level_4/task_10/CalculatorTest.java
src/main/java/students/georgy_bakulin/lesson_4/level_4/task_10/Main.java

Lesson 4, Level 4 , Task 10-14
